name: Node CI

on: [push]

jobs:
  build:
    name: Build & test

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo ::set-output name=nvm_node_version::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js ${{ steps.nvm.outputs.nvm_node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.nvm_node_version }}

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Test
      run: yarn test
